/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as UUsernameRouteImport } from './routes/u/$username'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedReservasRouteImport } from './routes/_authenticated/reservas'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedInicioRouteImport } from './routes/_authenticated/inicio'
import { Route as AuthenticatedFofoquinhasRouteImport } from './routes/_authenticated/fofoquinhas'
import { Route as AuthenticatedCarteiraRouteImport } from './routes/_authenticated/carteira'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedMimosRouteImport } from './routes/_authenticated/mimos'
import { Route as AuthenticatedEventosRouteImport } from './routes/_authenticated/eventos'
import { Route as AuthenticatedCheckinRouteImport } from './routes/_authenticated/checkin'
import { Route as AuthenticatedStaffCheckinRouteImport } from './routes/_authenticated/staff/checkin'

const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedReservasRoute = AuthenticatedReservasRouteImport.update({
  id: '/reservas',
  path: '/reservas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInicioRoute = AuthenticatedInicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFofoquinhasRoute =
  AuthenticatedFofoquinhasRouteImport.update({
    id: '/fofoquinhas',
    path: '/fofoquinhas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCarteiraRoute = AuthenticatedCarteiraRouteImport.update({
  id: '/carteira',
  path: '/carteira',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMimosRoute = AuthenticatedMimosRouteImport.update({
  id: '/mimos',
  path: '/mimos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEventosRoute = AuthenticatedEventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCheckinRoute = AuthenticatedCheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStaffCheckinRoute = AuthenticatedStaffCheckinRouteImport.update({
  id: '/staff/checkin',
  path: '/staff/checkin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/u/$username': typeof UUsernameRoute
  '/checkin': typeof AuthenticatedCheckinRoute
  '/eventos': typeof AuthenticatedEventosRoute
  '/mimos': typeof AuthenticatedMimosRoute
  '/staff/checkin': typeof AuthenticatedStaffCheckinRoute
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/carteira': typeof AuthenticatedCarteiraRoute
  '/fofoquinhas': typeof AuthenticatedFofoquinhasRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/reservas': typeof AuthenticatedReservasRoute
}
export interface FileRoutesByTo {
  '/u/$username': typeof UUsernameRoute
  '/checkin': typeof AuthenticatedCheckinRoute
  '/eventos': typeof AuthenticatedEventosRoute
  '/mimos': typeof AuthenticatedMimosRoute
  '/staff/checkin': typeof AuthenticatedStaffCheckinRoute
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/carteira': typeof AuthenticatedCarteiraRoute
  '/fofoquinhas': typeof AuthenticatedFofoquinhasRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/reservas': typeof AuthenticatedReservasRoute
}
export interface FileRoutesById {
  '/u/$username': typeof UUsernameRoute
  '/_authenticated/checkin': typeof AuthenticatedCheckinRoute
  '/_authenticated/eventos': typeof AuthenticatedEventosRoute
  '/_authenticated/mimos': typeof AuthenticatedMimosRoute
  '/_authenticated/staff/checkin': typeof AuthenticatedStaffCheckinRoute
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/carteira': typeof AuthenticatedCarteiraRoute
  '/_authenticated/fofoquinhas': typeof AuthenticatedFofoquinhasRoute
  '/_authenticated/inicio': typeof AuthenticatedInicioRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/reservas': typeof AuthenticatedReservasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/u/$username'
    | '/'
    | '/auth'
    | '/reset-password'
    | '/checkin'
    | '/eventos'
    | '/mimos'
    | '/staff/checkin'
    | '/admin'
    | '/carteira'
    | '/fofoquinhas'
    | '/inicio'
    | '/perfil'
    | '/reservas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/u/$username'
    | '/'
    | '/auth'
    | '/reset-password'
    | '/checkin'
    | '/eventos'
    | '/mimos'
    | '/staff/checkin'
    | '/admin'
    | '/carteira'
    | '/fofoquinhas'
    | '/inicio'
    | '/perfil'
    | '/reservas'
  id:
    | '__root__'
    | '/u/$username'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/checkin'
    | '/_authenticated/eventos'
    | '/_authenticated/mimos'
    | '/_authenticated/staff/checkin'
    | '/_authenticated/admin'
    | '/_authenticated/carteira'
    | '/_authenticated/fofoquinhas'
    | '/_authenticated/inicio'
    | '/_authenticated/perfil'
    | '/_authenticated/reservas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  UUsernameRoute: typeof UUsernameRoute
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/reservas': {
      id: '/_authenticated/reservas'
      path: '/reservas'
      fullPath: '/reservas'
      preLoaderRoute: typeof AuthenticatedReservasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inicio': {
      id: '/_authenticated/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof AuthenticatedInicioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fofoquinhas': {
      id: '/_authenticated/fofoquinhas'
      path: '/fofoquinhas'
      fullPath: '/fofoquinhas'
      preLoaderRoute: typeof AuthenticatedFofoquinhasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/carteira': {
      id: '/_authenticated/carteira'
      path: '/carteira'
      fullPath: '/carteira'
      preLoaderRoute: typeof AuthenticatedCarteiraRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checkin': {
      id: '/_authenticated/checkin'
      path: '/checkin'
      fullPath: '/checkin'
      preLoaderRoute: typeof AuthenticatedCheckinRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/eventos': {
      id: '/_authenticated/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof AuthenticatedEventosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mimos': {
      id: '/_authenticated/mimos'
      path: '/mimos'
      fullPath: '/mimos'
      preLoaderRoute: typeof AuthenticatedMimosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff/checkin': {
      id: '/_authenticated/staff/checkin'
      path: '/staff/checkin'
      fullPath: '/staff/checkin'
      preLoaderRoute: typeof AuthenticatedStaffCheckinRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCheckinRoute: typeof AuthenticatedCheckinRoute
  AuthenticatedEventosRoute: typeof AuthenticatedEventosRoute
  AuthenticatedMimosRoute: typeof AuthenticatedMimosRoute
  AuthenticatedStaffCheckinRoute: typeof AuthenticatedStaffCheckinRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedCarteiraRoute: typeof AuthenticatedCarteiraRoute
  AuthenticatedFofoquinhasRoute: typeof AuthenticatedFofoquinhasRoute
  AuthenticatedInicioRoute: typeof AuthenticatedInicioRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedReservasRoute: typeof AuthenticatedReservasRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCheckinRoute: AuthenticatedCheckinRoute,
  AuthenticatedEventosRoute: AuthenticatedEventosRoute,
  AuthenticatedMimosRoute: AuthenticatedMimosRoute,
  AuthenticatedStaffCheckinRoute: AuthenticatedStaffCheckinRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedCarteiraRoute: AuthenticatedCarteiraRoute,
  AuthenticatedFofoquinhasRoute: AuthenticatedFofoquinhasRoute,
  AuthenticatedInicioRoute: AuthenticatedInicioRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedReservasRoute: AuthenticatedReservasRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  UUsernameRoute: UUsernameRoute,
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
